### ISSUE TITLE
Crash (exception) when updating firmware

### ISSUE THREAD

**Issue by JF002** [TailyFair/InfiniWindows#1]
Hi! And thank you for your job on this companion app for InfiniTime!

I've just tried it on my Windows 10 computer : it connects to the watch and sets the time without any issue, great!

However, it crash (because of an unhandled exception) when I try to update the firmware. Here's the output:

```
Enter path to firmware zip archive: pinetime-mcuboot-app-dfu-1.11.0.zip
Sending ('Start DFU' (0x01), 'Application' (0x04)) to DFU Control Point
Error accessing service.
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument )
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 , Func`2 , Boolean& )
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 , Func`2 )
   at InfiniWindows.BaseBleService.WriteBytesAsync(String uuid, Byte[] bytes, Nullable`1 option)
   at InfiniWindows.FirmwareUpdateService.RunStepOneAsync()
   at InfiniWindows.FirmwareUpdateService.UpdateAsync()
   at Program.RunUpdateFirmwareAsync(DeviceManager deviceManager)
   at Program.Main(String[] args)
   at Program.<Main>(String[] args)
```

I tried entering relative and absolute paths, with the same result.

**Comment by TailyFair** [comment]
Thanks for testing the app! I really appreciate it.

Did this happened just once, sometimes or every time?

Error seems to be regarding to having some access to BLE services. Current error message is not enough to understand exactly what or why was not available for access.

I will add new release with improved logging this week, maybe it will help to find root cause of this.

**Comment by JF002** [comment]
It happened every time I tried to update the firmware. 
I'll try again again when the next release will be available, then :)
